site_name: Mapzen Android SDK
docs_dir: src-android
site_dir: dist-android

pages:
  - Home: index.md
  - 'Installation': 'installation.md'
  - 'Get started': 'getting-started.md'
  - 'Position, rotation, and zoom': 'basic-functions.md'
  - 'Add features': 'features.md'
  - 'Switching styles': 'styles.md'
  - 'Gesture responders': 'gesture-responders.md'
  - 'Location services': 'location-services.md'
  - LOST:
    - 'Getting started': 'getting-started.md'
    - 'Getting the Last Known Location': 'lost/last-known-location.md'
    - 'Receiving Location Updates': 'lost/location-updates.md'
    - 'Mock Locations & Routes': 'lost/mock-locations-routes.md'
    - 'Changing Location Settings': 'lost/location-settings.md'
    - 'Creating and Monitoring Geofences': 'lost/geofences.md'
  - Mapzen Places for Android:
    - 'Overview': 'places.md'
    - 'Autocomplete interface': 'autocomplete-ui.md'
    - 'GeoData API': 'geodata-api.md'
  - 'Mapzen Search for Android': 'search.md'
  - 'Mapzen Turn-by-Turn for Android': 'turn-by-turn.md'
  - 'Javadoc': 'javadoc.md'

mz:redirects:
  'markers': 'add-features'
  'polylines': 'add-features'
  'polygons': 'add-features'
  'current-location': 'location-services'

extra:
  site_subtitle: 'A thin wrapper that packages up everything you need to use Mapzen services in your Android applications.'
  project_repo_url: https://github.com/mapzen/android
  docs_base_url: https://github.com/mapzen/android/tree/master/docs
